name: Base API CI/CD

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'PRODUCTION' || 'STAGING' }}
    steps:
      - name: Say Hello!
        run: |
          if [[ "${{ secrets.TRELLO_SECRET_KEY }}" == "123" ]]; then
            echo "Es 123"
          else
            echo "No es 123"
          fi