name: Deploy Actions

on:
  workflow_dispatch

jobs:
  production:
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use OpenJDK
          java-version: '22'

      - name: Create tmp directory
        run: |
          mkdir -p ~/tmp
          chmod 777 ~/tmp

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Build with Maven
        run: mvn clean install
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}


