name: Deploy Actions

on:
  workflow_dispatch

jobs:
  production:
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
      - name: Getting my App name
        run: echo "On Production environment, my app name is ${{ vars.APP_NAME }}"

      - name: Getting Trello Board ID
        run: echo "On Production environment, board ID is ${{ vars.TRELLO_BOARD_ID }}"

      - name: Getting Main List ID
        run: echo "On Production environment, main publish list ID is ${{ vars.TRELLO_LIST_ID }}"

      - name: Getting Trello Secret Key & Token
        run:
          echo "${{ secrets.TRELLO_TOKEN }}" &
          echo "${{ secrets.TRELLO_SECRET_KEY }}"

  staging:
    runs-on: ubuntu-latest
    environment: STAGING

    steps:
      - name: Getting my App name
        run: echo "On Staging environment, my app name is ${{ vars.APP_NAME }}"

      - name: Getting Trello Board ID
        run: echo "On Staging environment, board ID is ${{ vars.TRELLO_BOARD_ID }}"

      - name: Getting Main List ID
        run: echo "On Staging environment, main publish list ID is ${{ vars.TRELLO_LIST_ID }}"

      - name: Getting Trello Secret Key & Token
        run:
          echo "${{ secrets.TRELLO_TOKEN }}" &
          echo "${{ secrets.TRELLO_SECRET_KEY }}"
