name: Base API CI/CD

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'PRODUCTION' || 'STAGING' }}
    steps:
      - name: Say Hello!
        run: echo "The secret is ${{ secrets.TRELLO_SECRET_KEY }}"