name: Base API CI/CD

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello!
        uses: echo "¡Hello! from GitHub Actions on branch ${{ github.ref }}"