name: Base API CI/CD

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello!
        run: echo "¡Hello! from GitHub Actions on branch ${{ github.ref }}"

      - name: Task name
        run: echo "This is a marged task"